---

- name: install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Installing docker==4.4.4 using pip
  pip:
    name: docker==4.4.4

- name: Pull nginx Docker image
  docker_image:
    name: nginx
    source: pull
- name: Create volume
  docker_volume:
      name: nginx-data
      driver: local
- name: Run nginx Docker container
  docker_container:
      name: nginx
      image: nginx
      state: started
      ports:
        - "80:80"
      volumes:
        - "nginx-data:/usr/share/nginx/html:ro"
