---
# tasks file for docker
# - name: Install Docker Engine
#   apt:
#     name: docker.io
#     state: present

  - name: update apt package index
    apt:
      update_cache: true
  - name: install docker package
    apt:
      name: docker.io
      state: present

  




      
# - name: Install Docker CLI
#   apt:
#     name: docker-compose
#     state: present
# - name: Start Docker service
#   service:
#     name: docker
#     state: started
#     enabled: true


    
